[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake",
    "mkl-devel",
    "ninja; platform_system!='Windows'",
    "oldest-supported-numpy",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["*-musl*", "pp*"]



[tool.cibuildwheel.linux]
before-all = [
    "sudo yum install boost-devel",
    "sudo cp build/linux-oneapi-yum-config /etc/yum.repos.d",
    "sudo yum install intel-basekit intel-basekit-32bit"
    ]