[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja; platform_system!='Windows'",
    "oldest-supported-numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["*-musl*", "pp*", "*i686*"]
build-verbosity = 1

[tool.cibuildwheel.macos]
before-all = "source $ONEAPI_SCRIPT"

[tool.cibuildwheel.linux]
before-all = [
    "yum install -y boost-devel",
    "bash build/install-mkl-linux.sh"
    ]