[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja; platform_system!='Windows'",
    "oldest-supported-numpy",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["*-musl*", "pp*"]
build-verbosity = 1

[tool.cibuildwheel.macos]
before-all = "source $ONEAPI_SCRIPT"
repair-wheel-command = ""

[tool.cibuildwheel.linux]
before-all = [
    "yum install -y boost-devel",
    "build/install-mkl-linux.sh"
    ]
repair-wheel-command = ""