[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake",
    "mkl-devel",
    "ninja; platform_system!='Windows'",
    "oldest-supported-numpy",
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["*-musl*", "pp*"]

[tool.cibuildwheel.macos]
before-all = "source $ONEAPI_SCRIPT"


[tool.cibuildwheel.linux]
before-all = [
    "yum install -y boost-devel",
    "cp -v build/linux-oneapi-yum-config /etc/yum.repos.d/oneAPI.repo",
    "yum install -y intel-basekit",
    "yum install -y intel-basekit-32bit"
    ]