[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake",
    "mkl-devel",
    "ninja; platform_system!='Windows'",
    "oldest-supported-numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["*-musl*", "pp*"]


[tool.cibuildwheel.linux]
before-all = "yum install boost-devel"