//
// Created by user on 09/12/22.
//

#ifndef ESIG_SRC_PYESIG_GET_VECTOR_CONSTRUCTION_DATA_H_
#define ESIG_SRC_PYESIG_GET_VECTOR_CONSTRUCTION_DATA_H_

#endif//ESIG_SRC_PYESIG_GET_VECTOR_CONSTRUCTION_DATA_H_
