name: Build esig

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]



    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get Boost x64
        id: boost
        run: choco install -no-progress -y boost-msvc-14.2
        if: runner.os == 'Windows'

      - name: Get Boost macos
        id: boost-macos
        run: brew install boost
        if: runner.os == 'macOS'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          BOOST_ROOTx86_64: ${{ steps.boost-x64.outputs.root }}
          BOOST_LIBRARYDIRx86_64: ${{ steps.boost-x64.outputs.librarydir }}
          BOOST_ROOTi386: ${{ steps.boost-x86.outputs.root }}
          BOOST_LIBRARYDIRi386: ${{ steps.boost-x86.outputs.librarydir }}
          RECOMBINE_USER: rolyp
          RECOMBINE_TOKEN: ${{ secrets.recombine_login }}

      - name: Cache outputs
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
