name: Build esig

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]



    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get Boost x64
        id: boost
        run: |
          nuget install boost-vc142 -Version 1.78.0 -OutputDirectory C:\local\
          echo "boost_root=C:\\local" >> $GITHUB_ENV
          ls C:\local\
#        run: |
#          choco install -no-progress -y boost-msvc-14.2
#          choco list -l
        if: runner.os == 'Windows'

      - name: Get Boost macos
        id: boost-macos
        run: brew install boost
        if: runner.os == 'macOS'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          BOOST_ROOT: ${{ env.boost_root }}
          RECOMBINE_USER: rolyp
          RECOMBINE_TOKEN: ${{ secrets.recombine_login }}

      - name: Cache outputs
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
