name: Build esig

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]



    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # In the future, this can be replaced by a download of the binary
      - name: Get recombine
        id: clone_recombine
        run: |
          bash ./build/git-preamble.sh
        continue-on-error: true
        env:
          RECOMBINE_USER: rolyp
          RECOMBINE_TOKEN: ${{ secrets.recombine_login }}

      - name: Get MKL
        if: runner.os == 'Windows' && steps.clone_recombine.outcome == 'success'
        shell: bash
        run: |
          curl -v -o /d/a/intel-mkl-installer.exe https://registrationcenter-download.intel.com/akdlm/irc_nas/18590/w_onemkl_p_2022.0.3.171_offline.exe
          ls /d/a/
          /d/a/intel-mkl-installer.exe -s -x -f /d/a/webimage_extracted --log extract.log
          ls /d/a/
          /d/a/webimage_extracted/bootstrapper.exe -s --action install --eula=accept  
          find -name mkl.h 


      - name: Get Boost x64
        id: boost
#        run: |
#          nuget install boost-vc142 -Version 1.78.0 -OutputDirectory C:\local\
#          echo "boost_root=C:\\local" >> $GITHUB_ENV
#          ls C:\local\
#        run: |
#          choco install -no-progress -y boost-msvc-14.2
#          choco list -l
        run: |
          vcpkg install boost-system:x86-windows
          vcpkg install boost-system:x64-windows
          vcpkg install boost-thread:x64-windows
          vcpkg install boost-thread:x86-windows
        if: runner.os == 'Windows'
#TODO: replace brew with vcpkg
      - name: Get Boost macos
        id: boost-macos
        run: brew install boost
        if: runner.os == 'macOS'


      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          BOOST_ROOT: ${{ env.boost_root }}
          MKLROOT: ${{ env.MKLROOT }}
          CMAKE_PREFIX_PATH: ${{ env.MKLROOT }}

      - name: Cache outputs
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
